In [1]:
import copy
import os
import json
import statistics
import time
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import torch
import logging

os.environ["VLLM_LOGGING_LEVEL"] = "ERROR"
logging.getLogger("vllm").setLevel(logging.ERROR)

from vllm import LLM, SamplingParams
from vllm.inputs import TokensPrompt
from PIL import Image



from transformers.generation import ContinuousBatchingConfig, ContinuousBatchingManager

/mnt/code/code/leosight-experiments/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# ===== User-configurable settings =====
MODEL_NAME = "Qwen/Qwen3-VL-2B-Instruct"
IMAGES_DIR = Path("images")
SYSTEM_PREFIX = "You are an assistant on board of a satellite who helps interpret disaster images."

# Multiple queries are run on each image.
QUERY_PROMPTS = [
    "Describe this image in detail. Include scene elements, objects, text, and spatial relationships.",
    "List the top 10 visible objects and where they are located in the image.",
    "What potential hazards or risks can you infer from this image?",
    "Summarize the scene in 3 concise bullet points.",
]

# Optional image filtering (set to empty tuple to allow all)
IMAGE_EXTENSIONS = (".png", ".jpg", ".jpeg", ".webp")

# Generation settings
MAX_TOKENS = 128
TEMPERATURE = 0.0

# Profiling controls
WARMUP_RUNS = 1
PROFILE_RUNS = 3

# Max number of distinct queries to send in one batched call.
# In continuous batching mode, queries are grouped into chunks of this size.
BATCH_SIZE = 4


# Visual token compression knobs (official processor pixel budget)
# Lower max_pixels -> fewer visual tokens -> faster but potentially less detail.
MAX_PIXELS = 512 * 512
MIN_PIXELS = 256 * 256

print('Configuration loaded.')

Configuration loaded.

In [ ]:
@dataclass
class ExperimentConfig:
    name: str
    enable_prefix_caching: bool
    use_continuous_batching: bool
    use_visual_token_compression: bool


EXPERIMENTS = [
    ExperimentConfig(
        name="baseline",
        enable_prefix_caching=False,
        use_continuous_batching=False,
        use_visual_token_compression=False,
    ),
    ExperimentConfig(
        name="continuous_batching_only",
        enable_prefix_caching=False,
        use_continuous_batching=True,
        use_visual_token_compression=False,
    ),
    ExperimentConfig(
        name="prefix_caching_only",
        enable_prefix_caching=True,
        use_continuous_batching=False,
        use_visual_token_compression=False,
    ),
    ExperimentConfig(
        name="visual_token_compression_only",
        enable_prefix_caching=False,
        use_continuous_batching=False,
        use_visual_token_compression=True,
    ),
    ExperimentConfig(
        name="cb_prefix_vtc",
        enable_prefix_caching=True,
        use_continuous_batching=True,
        use_visual_token_compression=True,
    ),
]


def get_image_paths(images_dir: Path):
    if not images_dir.exists():
        raise FileNotFoundError(f"Images directory not found: {images_dir.resolve()}")

    paths = []
    for p in sorted(images_dir.iterdir()):
        if p.is_file() and (not IMAGE_EXTENSIONS or p.suffix.lower() in IMAGE_EXTENSIONS):
            paths.append(p.resolve())

    if not paths:
        raise ValueError(f"No image files found in {images_dir.resolve()}")

    return paths




def build_llm(config: ExperimentConfig):


    mm_processor_kwargs = {}


    if config.use_visual_token_compression:
        mm_processor_kwargs["max_pixels"] = MAX_PIXELS
        mm_processor_kwargs["min_pixels"] = MIN_PIXELS


    llm = LLM(
        model=MODEL_NAME,
        # Enable prefix caching at the engine level if requested
        enable_prefix_caching=config.enable_prefix_caching,
        max_model_len = 4096,
        tensor_parallel_size=2, 
        mm_processor_kwargs=mm_processor_kwargs,
    )
    return {"model": llm}


def run_once(llm_bundle, config: ExperimentConfig, image_path: Path, query_batch: list[str]):
    llm = llm_bundle["model"]

    if not query_batch:
        raise ValueError("query_batch cannot be empty")

    with Image.open(image_path) as img:
        base_image = img.convert("RGB")

    sampling_params = SamplingParams(
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE if TEMPERATURE > 0 else 0.0,
    )

    # Build vLLM inputs: each prompt is a dict with "prompt" text + "multi_modal_data"
    prompts = []
    for query_text in query_batch:
        messages = [
            {"role": "system", "content": SYSTEM_PREFIX},
            {
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": "placeholder"}},
                    {"type": "text", "text": query_text},
                ],
            },
        ]
        # Use the model's chat template via vLLM's tokenizer
        prompt_text = llm.get_tokenizer().apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        prompts.append({
            "prompt": prompt_text,
            "multi_modal_data": {"image": base_image.copy()},
        })

    t0 = time.perf_counter()
    outputs = llm.generate(prompts, sampling_params=sampling_params)
    t1 = time.perf_counter()

    per_query = []
    total_output_tokens = 0

    for i, request_output in enumerate(outputs):
        # vLLM returns RequestOutput; use the first (and only) CompletionOutput
        completion = request_output.outputs[0]

        prompt_tokens = len(request_output.prompt_token_ids)
        output_tokens = len(completion.token_ids)
        total_output_tokens += output_tokens

        per_query.append({
            "query_text": query_batch[i],
            "prompt_tokens": prompt_tokens,
            "output_tokens": output_tokens,
            "sample_text": completion.text.strip()[:240],
        })

    elapsed_s = t1 - t0
    tok_per_s = (total_output_tokens / elapsed_s) if elapsed_s > 0 else 0.0
    prompt_lens = [x["prompt_tokens"] for x in per_query]

    return {
        "elapsed_s": elapsed_s,
        "requests_in_call": len(query_batch),
        "avg_prompt_tokens": float(statistics.mean(prompt_lens)) if prompt_lens else 0.0,
        "avg_output_tokens": float(statistics.mean([x["output_tokens"] for x in per_query])) if per_query else 0.0,
        "total_output_tokens": total_output_tokens,
        "throughput_output_tok_per_s": tok_per_s,
        "avg_first_token_latency_s": None,  # Not available in offline mode; use AsyncEngine for TTFT
        "items": per_query,
    }


print("Helpers ready.")

Helpers ready.

In [4]:
image_paths = get_image_paths(IMAGES_DIR)
query_prompts = QUERY_PROMPTS
query_to_idx = {q: i for i, q in enumerate(query_prompts, start=1)}

print(f"Found {len(image_paths)} images in {IMAGES_DIR.resolve()}")
for p in image_paths:
    print(f"  - {p.name}")

print(f"\nUsing {len(query_prompts)} queries per image")
for i, q in enumerate(query_prompts, start=1):
    print(f"  Q{i}: {q}")

all_raw_runs = []
summary_rows = []

for exp in EXPERIMENTS:
    print(f'\n=== Running experiment: {exp.name} ===')

    llm_bundle = build_llm(exp)

    batch_size = BATCH_SIZE if exp.use_continuous_batching else 1
    print(f"Batch size for this experiment: {batch_size}")

    # Warmup on first image and first query.
    for i in range(WARMUP_RUNS):
        _ = run_once(llm_bundle, exp, image_paths[0], [query_prompts[0]])
        print(f'  warmup {i + 1}/{WARMUP_RUNS} complete')


    run_metrics = []
    for image_path in image_paths:
        for i in range(PROFILE_RUNS):
            batch_metrics_this_run = []

            for start in range(0, len(query_prompts), batch_size):
                query_batch = query_prompts[start : start + batch_size]
                metrics = run_once(llm_bundle, exp, image_path, query_batch)
                batch_metrics_this_run.append(metrics)

                for item in metrics["items"]:
                    all_raw_runs.append(
                        {
                            "experiment": exp.name,
                            "image_name": image_path.name,
                            "query_idx": query_to_idx[item["query_text"]],
                            "query_text": item["query_text"],
                            "run_idx": i + 1,
                            "elapsed_s": metrics["elapsed_s"],
                            "requests_in_call": metrics["requests_in_call"],
                            "avg_prompt_tokens": float(item["prompt_tokens"]),
                            "avg_output_tokens": float(item["output_tokens"]),
                            "total_output_tokens": metrics["total_output_tokens"],
                            "throughput_output_tok_per_s": metrics["throughput_output_tok_per_s"],
                            "avg_first_token_latency_s": metrics["avg_first_token_latency_s"],
                            "sample_text": item["sample_text"],
                        }
                    )

                print(
                    f"  {image_path.name} | Q{query_to_idx[query_batch[0]]}-Q{query_to_idx[query_batch[-1]]} "
                    f"| run {i + 1}/{PROFILE_RUNS}: {metrics['elapsed_s']:.3f}s"
                )

        # Aggregate all batches for this (image, run) into one comparable metric
        total_elapsed = sum(m["elapsed_s"] for m in batch_metrics_this_run)
        total_output_tokens = sum(m["total_output_tokens"] for m in batch_metrics_this_run)
        all_items = [item for m in batch_metrics_this_run for item in m["items"]]
        ftl_vals_run = [m["avg_first_token_latency_s"] for m in batch_metrics_this_run if m["avg_first_token_latency_s"] is not None]

        run_metrics.append({
            "elapsed_s": total_elapsed,
            "total_output_tokens": total_output_tokens,
            "requests_in_call": len(all_items),
            "throughput_output_tok_per_s": total_output_tokens / total_elapsed if total_elapsed > 0 else 0.0,
            "avg_first_token_latency_s": statistics.mean(ftl_vals_run) if ftl_vals_run else None,
        })

        print(
            f"  {image_path.name} | run {i + 1}/{PROFILE_RUNS} total: {total_elapsed:.3f}s "
            f"({total_output_tokens} tokens, {run_metrics[-1]['throughput_output_tok_per_s']:.1f} tok/s)"
        )

    # Aggregate across all calls for this experiment.
    elapsed_vals = [r['elapsed_s'] for r in run_metrics]
    tps_vals = [r['throughput_output_tok_per_s'] for r in run_metrics]
    ftl_vals = [r['avg_first_token_latency_s'] for r in run_metrics if r['avg_first_token_latency_s'] is not None]

    summary_rows.append({
        "experiment": exp.name,
        "use_continuous_batching": exp.use_continuous_batching,
        "enable_prefix_caching": exp.enable_prefix_caching,
        "use_visual_token_compression": exp.use_visual_token_compression,
        "images_count": len(image_paths),
        "queries_per_image": len(query_prompts),
        "runs_per_query": PROFILE_RUNS,
        "total_samples": len(run_metrics),
        "mean_elapsed_s": statistics.mean(elapsed_vals),
        "stdev_elapsed_s": statistics.pstdev(elapsed_vals) if len(elapsed_vals) > 1 else 0.0,
        "mean_output_tok_per_s": statistics.mean(tps_vals),
        "mean_first_token_latency_s": statistics.mean(ftl_vals) if ftl_vals else None,
        "requests_per_call": run_metrics[0]['requests_in_call'] if run_metrics else None,
    })

    # Release engine before next config to reduce memory pressure.
    del llm_bundle

results_df = pd.DataFrame(summary_rows).sort_values('mean_elapsed_s')
raw_runs_df = pd.DataFrame(all_raw_runs)

display(results_df)
print('\nRaw run-level metrics:')
display(raw_runs_df)

Found 10 images in /mnt/code/code/leosight-experiments/images
  - guatemala-volcano_00000003_post_disaster.png
  - guatemala-volcano_00000003_pre_disaster.png
  - guatemala-volcano_00000005_post_disaster.png
  - guatemala-volcano_00000005_pre_disaster.png
  - guatemala-volcano_00000009_post_disaster.png
  - guatemala-volcano_00000009_pre_disaster.png
  - guatemala-volcano_00000011_post_disaster.png
  - guatemala-volcano_00000011_pre_disaster.png
  - guatemala-volcano_00000021_post_disaster.png
  - guatemala-volcano_00000021_pre_disaster.png

Using 4 queries per image
  Q1: Describe this image in detail. Include scene elements, objects, text, and spatial relationships.
  Q2: List the top 10 visible objects and where they are located in the image.
  Q3: What potential hazards or risks can you infer from this image?
  Q4: Summarize the scene in 3 concise bullet points.

=== Running experiment: baseline ===

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
[transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.

[Gloo] Rank [Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 11 is connected to
1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1

(Worker pid=1923934) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1923933) (Worker pid=1923934) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
<frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
(Worker pid=1923933) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.77it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.76it/s]
(Worker_TP0 pid=1923933)
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 25.49it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 30.62it/s]

Batch size for this experiment: 1

Rendering prompts: 100%|██████████| 1/1 [00:03<00:00,  3.17s/it]
Processed prompts: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it, est. speed input: 1022.64 toks/s, output: 122.10 toks/s]

  warmup 1/1 complete

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 115.11it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1756.69 toks/s, output: 209.75 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 1/3: 0.623s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 114.52it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1769.78 toks/s, output: 211.51 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 1/3: 0.618s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 115.37it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1764.29 toks/s, output: 211.84 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 1/3: 0.617s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.32it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.16it/s, est. speed input: 2305.21 toks/s, output: 201.10 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 1/3: 0.472s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 29.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1771.72 toks/s, output: 211.54 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 2/3: 0.643s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.52it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1770.80 toks/s, output: 211.63 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 2/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.71it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1763.06 toks/s, output: 211.69 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 2/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.50it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.16it/s, est. speed input: 2303.17 toks/s, output: 200.92 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 2/3: 0.473s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.92it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1793.42 toks/s, output: 214.13 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 3/3: 0.608s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.97it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1791.85 toks/s, output: 214.14 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 3/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1782.46 toks/s, output: 214.02 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 3/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.09it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.19it/s, est. speed input: 2340.57 toks/s, output: 204.19 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 3/3: 0.468s
  guatemala-volcano_00000003_post_disaster.png | run 3/3 total: 2.296s (477 tokens, 207.8 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1504.65 toks/s, output: 179.65 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 1/3: 0.784s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1790.85 toks/s, output: 214.03 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 1/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.09it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1763.13 toks/s, output: 211.70 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 1/3: 0.617s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.95it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.33it/s, est. speed input: 2489.71 toks/s, output: 200.85 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 1/3: 0.440s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1792.07 toks/s, output: 213.97 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.32it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1790.75 toks/s, output: 214.01 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.32it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1783.90 toks/s, output: 214.19 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 2/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 124.48it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.33it/s, est. speed input: 2493.85 toks/s, output: 201.18 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 2/3: 0.439s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 118.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1791.91 toks/s, output: 213.95 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.70it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1790.76 toks/s, output: 214.01 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 3/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 108.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1780.34 toks/s, output: 213.77 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 3/3: 0.612s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.01it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.33it/s, est. speed input: 2493.02 toks/s, output: 201.11 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 3/3: 0.440s
  guatemala-volcano_00000003_pre_disaster.png | run 3/3 total: 2.273s (470 tokens, 206.8 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1505.06 toks/s, output: 179.70 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 1/3: 0.794s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.73it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1789.59 toks/s, output: 213.87 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 1/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.50it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1781.71 toks/s, output: 213.93 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 1/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.94it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s, est. speed input: 2974.86 toks/s, output: 192.55 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 1/3: 0.370s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.56it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1791.16 toks/s, output: 213.86 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.49it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1788.04 toks/s, output: 213.69 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.68it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1780.69 toks/s, output: 213.81 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 2/3: 0.609s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.37it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s, est. speed input: 2968.65 toks/s, output: 192.14 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 2/3: 0.369s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 110.28it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1792.65 toks/s, output: 214.04 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 3/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 111.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1789.91 toks/s, output: 213.91 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 112.24it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1780.55 toks/s, output: 213.79 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 111.49it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s, est. speed input: 2974.09 toks/s, output: 192.49 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 3/3: 0.371s
  guatemala-volcano_00000005_post_disaster.png | run 3/3 total: 2.203s (453 tokens, 205.6 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1506.82 toks/s, output: 179.91 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 1/3: 0.796s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.14it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1790.25 toks/s, output: 213.95 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 1/3: 0.608s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.19it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1780.85 toks/s, output: 213.83 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 1/3: 0.609s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.88it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.74it/s, est. speed input: 2931.00 toks/s, output: 192.46 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 1/3: 0.374s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 130.95it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1789.10 toks/s, output: 213.62 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 2/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.60it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1790.10 toks/s, output: 213.93 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 2/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1782.29 toks/s, output: 214.00 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 2/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.90it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.75it/s, est. speed input: 2940.09 toks/s, output: 193.05 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 2/3: 0.374s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.91it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1790.07 toks/s, output: 213.73 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 124.61it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1787.95 toks/s, output: 213.68 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.92it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1779.48 toks/s, output: 213.66 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.75it/s, est. speed input: 2939.60 toks/s, output: 193.02 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 3/3: 0.375s
  guatemala-volcano_00000005_pre_disaster.png | run 3/3 total: 2.207s (454 tokens, 205.7 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1506.29 toks/s, output: 179.85 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 1/3: 0.787s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1789.49 toks/s, output: 213.86 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 1/3: 0.610s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.71it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1780.49 toks/s, output: 213.78 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 1/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 125.14it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s, est. speed input: 2872.84 toks/s, output: 194.03 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 1/3: 0.383s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1788.94 toks/s, output: 213.60 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1787.21 toks/s, output: 213.59 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.75it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1781.75 toks/s, output: 213.94 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 2/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.16it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s, est. speed input: 2870.35 toks/s, output: 193.86 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 2/3: 0.383s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1789.32 toks/s, output: 213.64 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 3/3: 0.611s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1789.39 toks/s, output: 213.85 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 3/3: 0.609s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 112.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1778.84 toks/s, output: 213.59 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 3/3: 0.612s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s, est. speed input: 2872.49 toks/s, output: 194.00 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 3/3: 0.383s
  guatemala-volcano_00000009_post_disaster.png | run 3/3 total: 2.214s (456 tokens, 205.9 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1505.10 toks/s, output: 179.71 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 1/3: 0.793s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.12it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1783.80 toks/s, output: 213.18 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 1/3: 0.612s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 126.85it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1773.19 toks/s, output: 212.91 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 1/3: 0.612s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 126.15it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.12it/s, est. speed input: 3340.22 toks/s, output: 184.86 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 1/3: 0.331s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 126.78it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1784.46 toks/s, output: 213.06 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 2/3: 0.612s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 127.25it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1782.65 toks/s, output: 213.05 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 2/3: 0.612s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 126.67it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1771.45 toks/s, output: 212.70 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 2/3: 0.613s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.83it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.11it/s, est. speed input: 3330.37 toks/s, output: 184.31 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 2/3: 0.331s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.72it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1784.65 toks/s, output: 213.09 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 3/3: 0.613s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.81it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1774.87 toks/s, output: 212.12 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 3/3: 0.613s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.61it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1768.64 toks/s, output: 212.36 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 3/3: 0.614s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.12it/s, est. speed input: 3332.57 toks/s, output: 184.44 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 3/3: 0.332s
  guatemala-volcano_00000009_pre_disaster.png | run 3/3 total: 2.172s (443 tokens, 203.9 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1497.72 toks/s, output: 178.83 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 1/3: 0.797s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.41it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1776.93 toks/s, output: 212.36 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 1/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.01it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1765.02 toks/s, output: 211.93 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 1/3: 0.616s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 135.79it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.28it/s, est. speed input: 3504.36 toks/s, output: 180.79 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 1/3: 0.315s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 130.21it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1764.71 toks/s, output: 210.70 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 2/3: 0.619s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.88it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1774.85 toks/s, output: 212.11 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 2/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.64it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1768.08 toks/s, output: 212.29 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 2/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.40it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.27it/s, est. speed input: 3501.34 toks/s, output: 180.64 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 2/3: 0.315s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.88it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1756.68 toks/s, output: 209.75 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 3/3: 0.623s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 124.12it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1777.50 toks/s, output: 212.43 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 3/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.35it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1767.48 toks/s, output: 212.22 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 3/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.27it/s, est. speed input: 3494.14 toks/s, output: 180.27 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 3/3: 0.317s
  guatemala-volcano_00000011_post_disaster.png | run 3/3 total: 2.170s (439 tokens, 202.3 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1494.47 toks/s, output: 178.44 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 1/3: 0.797s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.27it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1742.12 toks/s, output: 208.20 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 1/3: 0.627s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.66it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1743.97 toks/s, output: 209.40 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 1/3: 0.621s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 124.87it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.17it/s, est. speed input: 3388.14 toks/s, output: 181.15 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 1/3: 0.326s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1768.30 toks/s, output: 211.13 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 2/3: 0.619s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.19it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1765.55 toks/s, output: 211.00 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 2/3: 0.619s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 127.19it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1755.70 toks/s, output: 210.81 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 2/3: 0.619s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.87it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.19it/s, est. speed input: 3406.74 toks/s, output: 182.15 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 2/3: 0.326s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.21it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1769.47 toks/s, output: 211.27 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 3/3: 0.618s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.99it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1768.49 toks/s, output: 211.35 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 3/3: 0.618s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 110.20it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1756.93 toks/s, output: 210.96 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 3/3: 0.620s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.20it/s, est. speed input: 3425.80 toks/s, output: 183.16 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 3/3: 0.617s
  guatemala-volcano_00000011_pre_disaster.png | run 3/3 total: 2.473s (441 tokens, 178.3 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1489.75 toks/s, output: 177.87 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 1/3: 0.800s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.85it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1774.54 toks/s, output: 212.08 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 1/3: 0.616s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.37it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1732.40 toks/s, output: 208.01 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 1/3: 0.628s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.15it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.77it/s, est. speed input: 2966.64 toks/s, output: 186.45 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 1/3: 0.371s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1739.70 toks/s, output: 207.72 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 2/3: 0.629s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.90it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1751.21 toks/s, output: 209.28 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 2/3: 0.624s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.49it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1748.58 toks/s, output: 209.95 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 2/3: 0.622s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.81it/s, est. speed input: 3001.96 toks/s, output: 188.67 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 2/3: 0.368s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.80it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1760.04 toks/s, output: 210.15 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 3/3: 0.622s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1760.13 toks/s, output: 210.35 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 3/3: 0.621s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 134.49it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1747.98 toks/s, output: 209.88 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 3/3: 0.621s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.83it/s, est. speed input: 3022.22 toks/s, output: 189.94 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 3/3: 0.365s
  guatemala-volcano_00000021_post_disaster.png | run 3/3 total: 2.228s (451 tokens, 202.4 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s, est. speed input: 1462.99 toks/s, output: 174.68 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 1/3: 0.813s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.03it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1774.79 toks/s, output: 212.11 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 1/3: 0.615s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.56it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1729.79 toks/s, output: 207.70 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 1/3: 0.628s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.92it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.56it/s, est. speed input: 2735.60 toks/s, output: 189.89 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 1/3: 0.402s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 122.32it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1745.11 toks/s, output: 208.36 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 2/3: 0.626s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1745.21 toks/s, output: 208.57 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 2/3: 0.625s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 126.13it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1736.94 toks/s, output: 208.55 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 2/3: 0.625s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.27it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.58it/s, est. speed input: 2758.08 toks/s, output: 191.45 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 2/3: 0.396s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.14it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1766.33 toks/s, output: 210.90 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 3/3: 0.619s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 121.66it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1737.88 toks/s, output: 207.69 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 3/3: 0.628s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 128.84it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1730.61 toks/s, output: 207.79 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 3/3: 0.627s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 119.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.56it/s, est. speed input: 2732.88 toks/s, output: 189.70 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 3/3: 0.402s
  guatemala-volcano_00000021_pre_disaster.png | run 3/3 total: 2.277s (458 tokens, 201.2 tok/s)

=== Running experiment: continuous_batching_only ===
[Gloo] Rank 1[Gloo] Rank  is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank [Gloo] Rank 01 is connected to  is connected to 11 peer ranks.  peer ranks. Expected number of connected peer ranks is : Expected number of connected peer ranks is : 11

(Worker pid=1926222) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1926222) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
(Worker pid=1926220) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1926220) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.87it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.86it/s]
(Worker_TP0 pid=1926220)
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 25.77it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 30.81it/s]

Batch size for this experiment: 4

Rendering prompts: 100%|██████████| 1/1 [00:03<00:00,  3.29s/it]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.11it/s, est. speed input: 1195.43 toks/s, output: 142.73 toks/s]

  warmup 1/1 complete

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 171.93it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.59it/s, est. speed input: 4913.80 toks/s, output: 548.27 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q4 | run 1/3: 0.897s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 73.70it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.65it/s, est. speed input: 4970.07 toks/s, output: 554.55 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q4 | run 2/3: 0.918s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 164.02it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.60it/s, est. speed input: 4922.82 toks/s, output: 549.28 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q4 | run 3/3: 0.896s
  guatemala-volcano_00000003_post_disaster.png | run 3/3 total: 0.896s (477 tokens, 532.3 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 47.35it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.13it/s, est. speed input: 4416.07 toks/s, output: 452.45 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q4 | run 1/3: 1.057s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 171.64it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.66it/s, est. speed input: 4983.41 toks/s, output: 510.57 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q4 | run 2/3: 0.885s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 161.68it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.63it/s, est. speed input: 4949.29 toks/s, output: 507.08 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q4 | run 3/3: 0.892s
  guatemala-volcano_00000003_pre_disaster.png | run 3/3 total: 0.892s (438 tokens, 491.1 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 47.61it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.11it/s, est. speed input: 4394.75 toks/s, output: 462.60 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q4 | run 1/3: 1.060s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 161.41it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.65it/s, est. speed input: 4968.14 toks/s, output: 522.95 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q4 | run 2/3: 0.889s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 165.91it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.57it/s, est. speed input: 4886.01 toks/s, output: 514.31 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q4 | run 3/3: 0.903s
  guatemala-volcano_00000005_post_disaster.png | run 3/3 total: 0.903s (450 tokens, 498.6 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 47.19it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.11it/s, est. speed input: 4395.26 toks/s, output: 466.77 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q4 | run 1/3: 1.061s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 168.34it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.63it/s, est. speed input: 4952.95 toks/s, output: 525.99 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q4 | run 2/3: 0.890s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 168.39it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.63it/s, est. speed input: 4947.93 toks/s, output: 525.46 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q4 | run 3/3: 0.891s
  guatemala-volcano_00000005_pre_disaster.png | run 3/3 total: 0.891s (454 tokens, 509.5 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 47.47it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.07it/s, est. speed input: 4348.33 toks/s, output: 460.76 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q4 | run 1/3: 1.071s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 166.43it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.57it/s, est. speed input: 4882.27 toks/s, output: 517.34 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q4 | run 2/3: 0.903s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 138.55it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.66it/s, est. speed input: 4979.91 toks/s, output: 527.69 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q4 | run 3/3: 0.890s
  guatemala-volcano_00000009_post_disaster.png | run 3/3 total: 0.890s (453 tokens, 508.8 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 44.92it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.10it/s, est. speed input: 4383.29 toks/s, output: 454.21 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q4 | run 1/3: 1.068s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 122.02it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.64it/s, est. speed input: 4963.74 toks/s, output: 514.37 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q4 | run 2/3: 0.897s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 119.00it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.66it/s, est. speed input: 4979.15 toks/s, output: 515.96 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q4 | run 3/3: 0.895s
  guatemala-volcano_00000009_pre_disaster.png | run 3/3 total: 0.895s (443 tokens, 494.9 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 46.70it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.12it/s, est. speed input: 4403.25 toks/s, output: 452.16 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q4 | run 1/3: 1.060s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 118.91it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.63it/s, est. speed input: 4945.79 toks/s, output: 507.87 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q4 | run 2/3: 0.901s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 118.82it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.65it/s, est. speed input: 4970.00 toks/s, output: 510.36 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q4 | run 3/3: 0.897s
  guatemala-volcano_00000011_post_disaster.png | run 3/3 total: 0.897s (439 tokens, 489.5 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 44.98it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.10it/s, est. speed input: 4380.30 toks/s, output: 469.27 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q4 | run 1/3: 1.069s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 122.04it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.60it/s, est. speed input: 4919.34 toks/s, output: 527.02 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q4 | run 2/3: 0.905s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 118.15it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.62it/s, est. speed input: 4941.44 toks/s, output: 529.39 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q4 | run 3/3: 0.902s
  guatemala-volcano_00000011_pre_disaster.png | run 3/3 total: 0.902s (458 tokens, 507.7 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 44.38it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.07it/s, est. speed input: 4355.90 toks/s, output: 459.53 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q4 | run 1/3: 1.075s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 166.16it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.55it/s, est. speed input: 4867.69 toks/s, output: 513.52 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q4 | run 2/3: 0.905s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 173.24it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.55it/s, est. speed input: 4862.60 toks/s, output: 512.98 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q4 | run 3/3: 0.905s
  guatemala-volcano_00000021_post_disaster.png | run 3/3 total: 0.905s (451 tokens, 498.3 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 46.12it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.05it/s, est. speed input: 4334.95 toks/s, output: 443.12 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q4 | run 1/3: 1.076s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 167.96it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.58it/s, est. speed input: 4896.86 toks/s, output: 500.56 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q4 | run 2/3: 0.900s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 172.60it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  4.56it/s, est. speed input: 4870.64 toks/s, output: 497.88 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q4 | run 3/3: 0.904s
  guatemala-volcano_00000021_pre_disaster.png | run 3/3 total: 0.904s (437 tokens, 483.5 tok/s)

=== Running experiment: prefix_caching_only ===
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1

(Worker pid=1927356) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1927356) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
(Worker pid=1927355) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1927355) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.85it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.85it/s]
(Worker_TP0 pid=1927355)
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 25.71it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 30.80it/s]

Batch size for this experiment: 1

Rendering prompts: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s, est. speed input: 1198.86 toks/s, output: 143.14 toks/s]

  warmup 1/1 complete

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.57it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1958.06 toks/s, output: 233.79 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 1/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 135.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1961.14 toks/s, output: 234.37 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 1/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.13it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1960.29 toks/s, output: 235.37 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 1/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.86it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.49it/s, est. speed input: 2658.40 toks/s, output: 231.91 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 1/3: 0.412s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.22it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1981.05 toks/s, output: 236.53 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 2/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 28.43it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1975.10 toks/s, output: 236.04 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 2/3: 0.581s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1958.12 toks/s, output: 235.11 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 2/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.28it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.59it/s, est. speed input: 2768.16 toks/s, output: 231.10 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 2/3: 0.395s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.51it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1990.03 toks/s, output: 237.61 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 3/3: 0.549s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.03it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1986.48 toks/s, output: 237.40 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 3/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.87it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1985.17 toks/s, output: 238.36 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 3/3: 0.548s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.71it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.62it/s, est. speed input: 2795.82 toks/s, output: 233.41 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 3/3: 0.392s
  guatemala-volcano_00000003_post_disaster.png | run 3/3 total: 2.039s (473 tokens, 232.0 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1508.08 toks/s, output: 180.06 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 1/3: 0.758s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.21it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1981.91 toks/s, output: 236.86 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 1/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.50it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1974.09 toks/s, output: 237.03 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 1/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.98it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.93it/s, est. speed input: 4207.21 toks/s, output: 228.89 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 1/3: 0.263s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1991.38 toks/s, output: 237.77 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 2/3: 0.549s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.61it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1980.58 toks/s, output: 236.70 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.30it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1971.49 toks/s, output: 236.72 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s, est. speed input: 3928.35 toks/s, output: 232.14 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 2/3: 0.282s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.15it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1983.21 toks/s, output: 236.79 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.70it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1976.25 toks/s, output: 236.18 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 3/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.67it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1928.57 toks/s, output: 231.56 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 3/3: 0.563s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 127.18it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s, est. speed input: 3925.27 toks/s, output: 231.96 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 3/3: 0.283s
  guatemala-volcano_00000003_pre_disaster.png | run 3/3 total: 1.950s (447 tokens, 229.2 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 19.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1496.77 toks/s, output: 178.71 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 1/3: 0.773s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.02it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1969.31 toks/s, output: 235.35 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 1/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 170.09it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1936.87 toks/s, output: 232.56 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 1/3: 0.560s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.85it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.35it/s, est. speed input: 3579.28 toks/s, output: 231.66 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 1/3: 0.308s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1984.96 toks/s, output: 237.00 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1968.98 toks/s, output: 235.31 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 2/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.24it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1947.28 toks/s, output: 233.81 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 2/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.95it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.02it/s, est. speed input: 3227.99 toks/s, output: 230.12 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 2/3: 0.339s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 170.58it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1963.57 toks/s, output: 234.45 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 3/3: 0.555s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1970.36 toks/s, output: 235.48 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 3/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 169.23it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1947.66 toks/s, output: 233.86 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 3/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.12it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.00it/s, est. speed input: 3211.87 toks/s, output: 228.97 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 3/3: 0.342s
  guatemala-volcano_00000005_post_disaster.png | run 3/3 total: 2.006s (460 tokens, 229.3 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1508.07 toks/s, output: 180.06 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 1/3: 0.765s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.64it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1962.86 toks/s, output: 234.58 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 1/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.95it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1936.54 toks/s, output: 232.52 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 1/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.32it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.24it/s, est. speed input: 3462.68 toks/s, output: 227.36 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 1/3: 0.318s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.92it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1952.44 toks/s, output: 233.12 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 2/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 129.64it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1981.82 toks/s, output: 236.85 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.14it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1951.29 toks/s, output: 234.29 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 2/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 142.55it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.24it/s, est. speed input: 3467.52 toks/s, output: 227.68 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 2/3: 0.318s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1952.75 toks/s, output: 233.15 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 3/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.44it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1954.41 toks/s, output: 233.57 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 3/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.06it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1945.21 toks/s, output: 233.56 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 3/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.96it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.25it/s, est. speed input: 3478.16 toks/s, output: 228.38 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 3/3: 0.317s
  guatemala-volcano_00000005_pre_disaster.png | run 3/3 total: 1.992s (454 tokens, 228.0 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, est. speed input: 1474.36 toks/s, output: 176.04 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 1/3: 0.782s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.15it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1944.91 toks/s, output: 232.44 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 1/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1932.65 toks/s, output: 232.05 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 1/3: 0.562s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.14it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.13it/s, est. speed input: 3350.77 toks/s, output: 226.30 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 1/3: 0.328s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.47it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1947.90 toks/s, output: 232.57 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 2/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.28it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1955.90 toks/s, output: 233.75 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 2/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.77it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1938.88 toks/s, output: 232.80 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 2/3: 0.560s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.99it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.23it/s, est. speed input: 3456.24 toks/s, output: 233.43 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 2/3: 0.319s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.45it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1983.39 toks/s, output: 236.81 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.86it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1958.91 toks/s, output: 234.11 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 3/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 163.96it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1939.31 toks/s, output: 232.85 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 3/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 130.45it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.16it/s, est. speed input: 3379.66 toks/s, output: 228.25 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 3/3: 0.326s
  guatemala-volcano_00000009_post_disaster.png | run 3/3 total: 1.993s (456 tokens, 228.8 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s, est. speed input: 1476.22 toks/s, output: 176.26 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 1/3: 0.781s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.44it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1952.95 toks/s, output: 233.40 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 1/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1949.70 toks/s, output: 234.10 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 1/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.47it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.82it/s, est. speed input: 4087.90 toks/s, output: 226.23 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 1/3: 0.270s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 170.47it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1967.82 toks/s, output: 234.95 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 2/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1967.65 toks/s, output: 235.15 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 2/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.24it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1944.66 toks/s, output: 233.50 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 2/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.69it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.69it/s, est. speed input: 3944.97 toks/s, output: 229.42 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 2/3: 0.279s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.22it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1976.62 toks/s, output: 236.00 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.86it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1952.88 toks/s, output: 233.39 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 3/3: 0.558s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.41it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1956.44 toks/s, output: 234.91 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 3/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.72it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.68it/s, est. speed input: 3934.57 toks/s, output: 228.82 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 3/3: 0.280s
  guatemala-volcano_00000009_pre_disaster.png | run 3/3 total: 1.944s (446 tokens, 229.5 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s, est. speed input: 1483.06 toks/s, output: 177.08 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 1/3: 0.775s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 170.99it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1960.66 toks/s, output: 234.32 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 1/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 169.81it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1966.56 toks/s, output: 236.13 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 1/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.13it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.50it/s, est. speed input: 4818.44 toks/s, output: 225.98 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 1/3: 0.230s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.88it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1992.50 toks/s, output: 237.90 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 2/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.68it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1988.65 toks/s, output: 237.66 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 2/3: 0.549s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.15it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1979.62 toks/s, output: 237.69 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 2/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.05it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.65it/s, est. speed input: 4978.12 toks/s, output: 228.80 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 2/3: 0.223s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.80it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1987.26 toks/s, output: 237.28 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 3/3: 0.548s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.36it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1988.76 toks/s, output: 237.68 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 3/3: 0.548s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.27it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1979.97 toks/s, output: 237.73 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 3/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.06it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.62it/s, est. speed input: 4951.43 toks/s, output: 227.57 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 3/3: 0.224s
  guatemala-volcano_00000011_post_disaster.png | run 3/3 total: 1.868s (433 tokens, 231.8 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1505.86 toks/s, output: 179.80 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 1/3: 0.764s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 141.10it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1977.38 toks/s, output: 236.32 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 1/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.27it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1965.65 toks/s, output: 236.02 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 1/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 175.63it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.12it/s, est. speed input: 3335.23 toks/s, output: 231.51 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 1/3: 0.329s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.90it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1993.78 toks/s, output: 238.05 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 2/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.00it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1989.52 toks/s, output: 237.77 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 2/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 174.20it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1979.58 toks/s, output: 237.69 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 2/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 174.67it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.15it/s, est. speed input: 3367.64 toks/s, output: 233.76 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 2/3: 0.326s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1990.65 toks/s, output: 237.68 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 3/3: 0.548s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 175.34it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1989.23 toks/s, output: 237.73 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 3/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.05it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1980.72 toks/s, output: 237.83 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 3/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 153.23it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.14it/s, est. speed input: 3358.69 toks/s, output: 233.14 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 3/3: 0.327s
  guatemala-volcano_00000011_pre_disaster.png | run 3/3 total: 1.969s (458 tokens, 232.6 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 20.53it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, est. speed input: 1508.89 toks/s, output: 180.16 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 1/3: 0.763s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 170.85it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1982.65 toks/s, output: 236.95 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 1/3: 0.549s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.70it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1968.98 toks/s, output: 236.42 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 1/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 176.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.44it/s, est. speed input: 3680.64 toks/s, output: 231.31 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 1/3: 0.299s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.61it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1996.12 toks/s, output: 238.33 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 2/3: 0.546s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 174.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1995.63 toks/s, output: 238.50 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 2/3: 0.546s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 175.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1982.39 toks/s, output: 238.03 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 2/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.82it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.46it/s, est. speed input: 3703.83 toks/s, output: 232.77 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 2/3: 0.298s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.25it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1994.26 toks/s, output: 238.11 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 3/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 177.00it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1994.70 toks/s, output: 238.39 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 3/3: 0.546s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 168.12it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1982.73 toks/s, output: 238.07 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 3/3: 0.547s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 175.28it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.45it/s, est. speed input: 3691.91 toks/s, output: 232.02 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 3/3: 0.298s
  guatemala-volcano_00000021_post_disaster.png | run 3/3 total: 1.937s (451 tokens, 232.8 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1496.86 toks/s, output: 178.72 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 1/3: 0.769s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.29it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1984.01 toks/s, output: 237.11 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 1/3: 0.549s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 173.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1975.88 toks/s, output: 237.25 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 1/3: 0.548s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 174.37it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.27it/s, est. speed input: 4568.14 toks/s, output: 227.10 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 1/3: 0.243s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 169.31it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1990.59 toks/s, output: 237.67 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 2/3: 0.548s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.13it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 1988.54 toks/s, output: 237.65 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 2/3: 0.549s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 174.81it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1967.89 toks/s, output: 236.28 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.34it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.39it/s, est. speed input: 4694.25 toks/s, output: 228.96 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 2/3: 0.237s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.18it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1980.11 toks/s, output: 236.42 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 3/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.54it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1975.95 toks/s, output: 236.15 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 3/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 172.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1984.76 toks/s, output: 238.31 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 3/3: 0.546s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 175.36it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.39it/s, est. speed input: 4705.61 toks/s, output: 229.51 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 3/3: 0.236s
  guatemala-volcano_00000021_pre_disaster.png | run 3/3 total: 1.885s (436 tokens, 231.3 tok/s)

=== Running experiment: visual_token_compression_only ===
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : [Gloo] Rank 1
0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1

(Worker pid=1929076) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1929075) (Worker pid=1929076) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
<frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1929075) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.80it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.79it/s]
(Worker_TP0 pid=1929075)
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 25.60it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 30.96it/s]

Batch size for this experiment: 1

Rendering prompts: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, est. speed input: 378.25 toks/s, output: 159.26 toks/s]

  warmup 1/1 complete

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 141.99it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 559.72 toks/s, output: 235.66 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 1/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 558.43 toks/s, output: 235.89 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 1/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.65it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 549.94 toks/s, output: 236.21 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 1/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.16it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.47it/s, est. speed input: 1036.68 toks/s, output: 226.10 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 1/3: 0.298s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 138.22it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 561.29 toks/s, output: 236.32 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 2/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.96it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 559.15 toks/s, output: 236.20 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 2/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.71it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 549.79 toks/s, output: 236.14 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 2/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 25.00it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.47it/s, est. speed input: 1037.11 toks/s, output: 226.20 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 2/3: 0.332s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 563.41 toks/s, output: 237.21 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q1 | run 3/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.27it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 561.46 toks/s, output: 237.18 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q2-Q2 | run 3/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.48it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 552.02 toks/s, output: 237.10 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q3-Q3 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 167.74it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.48it/s, est. speed input: 1041.81 toks/s, output: 227.22 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q4-Q4 | run 3/3: 0.296s
  guatemala-volcano_00000003_post_disaster.png | run 3/3 total: 1.947s (449 tokens, 230.6 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 52.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.74it/s, est. speed input: 530.49 toks/s, output: 223.35 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 1/3: 0.597s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.37it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 558.39 toks/s, output: 235.88 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 1/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.47it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 551.52 toks/s, output: 236.88 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 1/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.67it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.59it/s, est. speed input: 1074.01 toks/s, output: 227.04 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 1/3: 0.288s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 562.92 toks/s, output: 237.01 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.86it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 561.04 toks/s, output: 237.00 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.64it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 551.76 toks/s, output: 236.99 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.47it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.59it/s, est. speed input: 1074.35 toks/s, output: 227.11 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 2/3: 0.288s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.16it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 563.02 toks/s, output: 237.05 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q1 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.21it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 560.66 toks/s, output: 236.83 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q2-Q2 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.82it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 551.41 toks/s, output: 236.84 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q3-Q3 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 144.66it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s, est. speed input: 1070.48 toks/s, output: 226.29 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q4-Q4 | run 3/3: 0.289s
  guatemala-volcano_00000003_pre_disaster.png | run 3/3 total: 1.940s (447 tokens, 230.4 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 60.77it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s, est. speed input: 534.43 toks/s, output: 225.01 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 1/3: 0.589s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 128.48it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 560.83 toks/s, output: 236.91 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 1/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 145.70it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 552.04 toks/s, output: 237.11 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 1/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.38it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.12it/s, est. speed input: 1232.87 toks/s, output: 223.38 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 1/3: 0.252s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.40it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 562.80 toks/s, output: 236.96 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 2/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 171.76it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 558.39 toks/s, output: 235.88 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 2/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.80it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 551.56 toks/s, output: 236.90 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 2/3: 0.550s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.69it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.13it/s, est. speed input: 1234.50 toks/s, output: 223.68 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 2/3: 0.251s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.01it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 562.61 toks/s, output: 236.88 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q1 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.94it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.85it/s, est. speed input: 560.63 toks/s, output: 236.82 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q2-Q2 | run 3/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.05it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 545.94 toks/s, output: 234.49 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q3-Q3 | run 3/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.32it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.13it/s, est. speed input: 1234.25 toks/s, output: 223.64 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q4-Q4 | run 3/3: 0.252s
  guatemala-volcano_00000005_post_disaster.png | run 3/3 total: 1.909s (438 tokens, 229.5 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 69.71it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s, est. speed input: 533.84 toks/s, output: 224.77 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 1/3: 0.587s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.67it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 559.10 toks/s, output: 236.18 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 1/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.03it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 549.96 toks/s, output: 236.21 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 1/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 152.38it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.87it/s, est. speed input: 1156.12 toks/s, output: 225.00 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 1/3: 0.267s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.62it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 561.45 toks/s, output: 236.39 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 2/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.66it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 559.66 toks/s, output: 236.42 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 2/3: 0.551s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.20it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 549.27 toks/s, output: 235.92 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 2/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 131.98it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.85it/s, est. speed input: 1150.21 toks/s, output: 223.85 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 2/3: 0.270s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.75it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 560.57 toks/s, output: 236.02 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q1 | run 3/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.68it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 559.24 toks/s, output: 236.24 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q2-Q2 | run 3/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.21it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 549.35 toks/s, output: 235.95 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q3-Q3 | run 3/3: 0.552s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.36it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.85it/s, est. speed input: 1152.65 toks/s, output: 224.32 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q4-Q4 | run 3/3: 0.268s
  guatemala-volcano_00000005_pre_disaster.png | run 3/3 total: 1.925s (442 tokens, 229.6 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 69.02it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s, est. speed input: 533.08 toks/s, output: 224.45 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 1/3: 0.588s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.04it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 558.44 toks/s, output: 235.90 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 1/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.73it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 548.65 toks/s, output: 235.65 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 1/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.81it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.42it/s, est. speed input: 1021.69 toks/s, output: 226.27 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 1/3: 0.301s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.20it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 559.71 toks/s, output: 235.65 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 2/3: 0.553s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 120.56it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 557.41 toks/s, output: 235.46 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 2/3: 0.555s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.59it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 546.75 toks/s, output: 234.84 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 2/3: 0.555s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.82it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.41it/s, est. speed input: 1020.54 toks/s, output: 226.01 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 2/3: 0.302s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.12it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 558.15 toks/s, output: 235.00 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q1 | run 3/3: 0.555s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.48it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 556.36 toks/s, output: 235.02 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q2-Q2 | run 3/3: 0.554s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.75it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 544.87 toks/s, output: 234.03 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q3-Q3 | run 3/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.15it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.40it/s, est. speed input: 1017.14 toks/s, output: 225.25 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q4-Q4 | run 3/3: 0.303s
  guatemala-volcano_00000009_post_disaster.png | run 3/3 total: 1.969s (450 tokens, 228.6 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 68.73it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.74it/s, est. speed input: 529.31 toks/s, output: 222.86 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 1/3: 0.592s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 130.39it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 555.00 toks/s, output: 234.45 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 1/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 544.67 toks/s, output: 233.94 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 1/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.96it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s, est. speed input: 1093.48 toks/s, output: 223.82 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 1/3: 0.282s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 175.59it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 555.73 toks/s, output: 233.98 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 2/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.48it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 551.78 toks/s, output: 233.09 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 2/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 542.15 toks/s, output: 232.86 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 2/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.17it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s, est. speed input: 1093.32 toks/s, output: 223.79 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 2/3: 0.282s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.02it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 553.95 toks/s, output: 233.23 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q1 | run 3/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.93it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 551.19 toks/s, output: 232.84 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q2-Q2 | run 3/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.63it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 540.87 toks/s, output: 232.31 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q3-Q3 | run 3/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.36it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.61it/s, est. speed input: 1079.81 toks/s, output: 221.02 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q4-Q4 | run 3/3: 0.286s
  guatemala-volcano_00000009_pre_disaster.png | run 3/3 total: 1.965s (445 tokens, 226.5 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 61.00it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.73it/s, est. speed input: 527.26 toks/s, output: 222.00 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 1/3: 0.596s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.59it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 550.01 toks/s, output: 232.34 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 1/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.78it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 539.89 toks/s, output: 231.89 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 1/3: 0.562s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.83it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.07it/s, est. speed input: 917.39 toks/s, output: 224.72 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 1/3: 0.335s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 146.35it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 548.01 toks/s, output: 230.73 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 2/3: 0.565s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 143.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 554.37 toks/s, output: 234.18 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 2/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.12it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 541.14 toks/s, output: 232.43 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 2/3: 0.560s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 133.64it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.06it/s, est. speed input: 913.37 toks/s, output: 223.73 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 2/3: 0.337s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 136.13it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 548.80 toks/s, output: 231.06 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q1 | run 3/3: 0.565s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 152.29it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 546.55 toks/s, output: 230.88 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q2-Q2 | run 3/3: 0.564s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.61it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 539.27 toks/s, output: 231.62 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q3-Q3 | run 3/3: 0.562s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.51it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.06it/s, est. speed input: 913.85 toks/s, output: 223.84 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q4-Q4 | run 3/3: 0.336s
  guatemala-volcano_00000011_post_disaster.png | run 3/3 total: 2.027s (457 tokens, 225.4 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 62.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s, est. speed input: 521.58 toks/s, output: 219.60 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 1/3: 0.603s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.44it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 548.29 toks/s, output: 231.61 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 1/3: 0.563s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.50it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 539.12 toks/s, output: 231.56 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 1/3: 0.563s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 154.10it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.78it/s, est. speed input: 1130.17 toks/s, output: 219.95 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 1/3: 0.274s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.06it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 549.69 toks/s, output: 231.44 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 2/3: 0.563s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.10it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 547.23 toks/s, output: 231.16 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 2/3: 0.564s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 538.45 toks/s, output: 231.27 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 2/3: 0.564s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.13it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.80it/s, est. speed input: 1136.59 toks/s, output: 221.20 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 2/3: 0.272s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.00it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 551.90 toks/s, output: 232.37 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q1 | run 3/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 153.68it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 549.16 toks/s, output: 231.98 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q2-Q2 | run 3/3: 0.561s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 147.98it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 541.36 toks/s, output: 232.52 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q3-Q3 | run 3/3: 0.560s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.46it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  3.79it/s, est. speed input: 1132.88 toks/s, output: 220.48 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q4-Q4 | run 3/3: 0.273s
  guatemala-volcano_00000011_pre_disaster.png | run 3/3 total: 1.955s (442 tokens, 226.0 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 61.49it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.73it/s, est. speed input: 527.12 toks/s, output: 221.93 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 1/3: 0.596s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 132.98it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 549.04 toks/s, output: 231.93 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 1/3: 0.563s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.34it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 539.89 toks/s, output: 231.89 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 1/3: 0.562s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 154.31it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s, est. speed input: 824.13 toks/s, output: 226.76 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 1/3: 0.371s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.31it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 552.21 toks/s, output: 232.50 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 2/3: 0.560s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.97it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 547.52 toks/s, output: 231.28 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 2/3: 0.563s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 149.93it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 541.69 toks/s, output: 232.66 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 2/3: 0.560s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 152.63it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.77it/s, est. speed input: 828.19 toks/s, output: 227.88 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 2/3: 0.370s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.85it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 555.87 toks/s, output: 234.04 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q1 | run 3/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 154.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 554.35 toks/s, output: 234.17 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q2-Q2 | run 3/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.95it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 537.63 toks/s, output: 230.92 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q3-Q3 | run 3/3: 0.564s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 177.61it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.79it/s, est. speed input: 834.07 toks/s, output: 229.50 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q4-Q4 | run 3/3: 0.366s
  guatemala-volcano_00000021_post_disaster.png | run 3/3 total: 2.043s (466 tokens, 228.1 tok/s)

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 62.58it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s, est. speed input: 523.92 toks/s, output: 220.59 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 1/3: 0.600s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 148.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 553.68 toks/s, output: 233.89 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 1/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.51it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 542.75 toks/s, output: 233.12 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 1/3: 0.559s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 152.10it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.46it/s, est. speed input: 1333.31 toks/s, output: 219.22 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 1/3: 0.233s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.77it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 556.02 toks/s, output: 234.11 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 2/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.96it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 553.77 toks/s, output: 233.93 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 2/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 180.49it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 544.53 toks/s, output: 233.88 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 2/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 135.28it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.45it/s, est. speed input: 1331.50 toks/s, output: 218.92 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 2/3: 0.234s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.92it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 556.10 toks/s, output: 234.14 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q1 | run 3/3: 0.556s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 154.01it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 553.62 toks/s, output: 233.86 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q2-Q2 | run 3/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 150.18it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 544.77 toks/s, output: 233.99 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q3-Q3 | run 3/3: 0.557s

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 151.81it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  4.47it/s, est. speed input: 1336.61 toks/s, output: 219.76 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q4-Q4 | run 3/3: 0.233s
  guatemala-volcano_00000021_pre_disaster.png | run 3/3 total: 1.903s (433 tokens, 227.5 tok/s)

=== Running experiment: cb_prefix_vtc ===
[Gloo] Rank [Gloo] Rank 01 is connected to 1 is connected to  peer ranks. 1Expected number of connected peer ranks is :  peer ranks. 1Expected number of connected peer ranks is : 1

[Gloo] Rank [Gloo] Rank 10 is connected to  is connected to 11 peer ranks.  peer ranks. Expected number of connected peer ranks is : Expected number of connected peer ranks is : 11

(Worker pid=1930672) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1930672) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
(Worker pid=1930671) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(Worker pid=1930671) <frozen importlib._bootstrap_external>:1241: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.83it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.83it/s]
(Worker_TP0 pid=1930671)
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 25.27it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 30.33it/s]

Batch size for this experiment: 4

Rendering prompts: 100%|██████████| 1/1 [00:03<00:00,  3.71s/it]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, est. speed input: 377.05 toks/s, output: 158.75 toks/s]

  warmup 1/1 complete

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 169.07it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.88it/s, est. speed input: 2071.44 toks/s, output: 785.17 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q4 | run 1/3: 0.608s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 171.04it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.05it/s, est. speed input: 2120.57 toks/s, output: 791.45 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q4 | run 2/3: 0.594s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 71.03it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.06it/s, est. speed input: 2125.08 toks/s, output: 793.14 toks/s]

  guatemala-volcano_00000003_post_disaster.png | Q1-Q4 | run 3/3: 0.626s
  guatemala-volcano_00000003_post_disaster.png | run 3/3 total: 0.626s (449 tokens, 717.0 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 120.95it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.53it/s, est. speed input: 1966.07 toks/s, output: 727.25 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q4 | run 1/3: 0.649s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 182.68it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.05it/s, est. speed input: 2121.40 toks/s, output: 788.24 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q4 | run 2/3: 0.593s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 171.38it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.03it/s, est. speed input: 2116.31 toks/s, output: 786.34 toks/s]

  guatemala-volcano_00000003_pre_disaster.png | Q1-Q4 | run 3/3: 0.595s
  guatemala-volcano_00000003_pre_disaster.png | run 3/3 total: 0.595s (447 tokens, 750.8 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 114.86it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.53it/s, est. speed input: 1966.60 toks/s, output: 716.01 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q4 | run 1/3: 0.650s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00,  9.82it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.08it/s, est. speed input: 2129.30 toks/s, output: 775.24 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q4 | run 2/3: 0.975s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 190.06it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.07it/s, est. speed input: 2128.03 toks/s, output: 774.78 toks/s]

  guatemala-volcano_00000005_post_disaster.png | Q1-Q4 | run 3/3: 0.590s
  guatemala-volcano_00000005_post_disaster.png | run 3/3 total: 0.590s (438 tokens, 743.0 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 117.36it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.55it/s, est. speed input: 1970.71 toks/s, output: 724.05 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q4 | run 1/3: 0.648s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 178.28it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.08it/s, est. speed input: 2130.53 toks/s, output: 782.77 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q4 | run 2/3: 0.591s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 167.78it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.02it/s, est. speed input: 2114.27 toks/s, output: 776.79 toks/s]

  guatemala-volcano_00000005_pre_disaster.png | Q1-Q4 | run 3/3: 0.596s
  guatemala-volcano_00000005_pre_disaster.png | run 3/3 total: 0.596s (442 tokens, 741.4 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 122.35it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.54it/s, est. speed input: 1967.23 toks/s, output: 735.86 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q4 | run 1/3: 0.648s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 168.85it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.01it/s, est. speed input: 2109.53 toks/s, output: 789.08 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q4 | run 2/3: 0.597s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 166.30it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.02it/s, est. speed input: 2113.47 toks/s, output: 790.55 toks/s]

  guatemala-volcano_00000009_post_disaster.png | Q1-Q4 | run 3/3: 0.597s
  guatemala-volcano_00000009_post_disaster.png | run 3/3 total: 0.597s (450 tokens, 753.9 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 115.65it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.55it/s, est. speed input: 1971.05 toks/s, output: 729.09 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q4 | run 1/3: 0.649s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 163.62it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.97it/s, est. speed input: 2097.76 toks/s, output: 775.95 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q4 | run 2/3: 0.601s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 166.23it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.08it/s, est. speed input: 2129.48 toks/s, output: 787.69 toks/s]

  guatemala-volcano_00000009_pre_disaster.png | Q1-Q4 | run 3/3: 0.592s
  guatemala-volcano_00000009_pre_disaster.png | run 3/3 total: 0.592s (445 tokens, 751.5 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 119.38it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.52it/s, est. speed input: 1961.55 toks/s, output: 748.40 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q4 | run 1/3: 0.650s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 164.59it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.07it/s, est. speed input: 2126.82 toks/s, output: 804.39 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q4 | run 2/3: 0.593s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 155.82it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.99it/s, est. speed input: 2102.59 toks/s, output: 795.22 toks/s]

  guatemala-volcano_00000011_post_disaster.png | Q1-Q4 | run 3/3: 0.601s
  guatemala-volcano_00000011_post_disaster.png | run 3/3 total: 0.601s (455 tokens, 757.3 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 121.82it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.53it/s, est. speed input: 1964.44 toks/s, output: 721.75 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q4 | run 1/3: 0.648s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 167.09it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.06it/s, est. speed input: 2123.49 toks/s, output: 785.48 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q4 | run 2/3: 0.594s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 166.95it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.06it/s, est. speed input: 2124.52 toks/s, output: 785.86 toks/s]

  guatemala-volcano_00000011_pre_disaster.png | Q1-Q4 | run 3/3: 0.593s
  guatemala-volcano_00000011_pre_disaster.png | run 3/3 total: 0.593s (445 tokens, 750.3 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 114.15it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.52it/s, est. speed input: 1963.51 toks/s, output: 745.89 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q4 | run 1/3: 0.651s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 171.03it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.05it/s, est. speed input: 2121.56 toks/s, output: 800.64 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q4 | run 2/3: 0.593s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 163.39it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.06it/s, est. speed input: 2124.50 toks/s, output: 801.75 toks/s]

  guatemala-volcano_00000021_post_disaster.png | Q1-Q4 | run 3/3: 0.594s
  guatemala-volcano_00000021_post_disaster.png | run 3/3 total: 0.594s (454 tokens, 764.6 tok/s)

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 117.95it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.50it/s, est. speed input: 1957.32 toks/s, output: 714.25 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q4 | run 1/3: 0.652s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 170.54it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  7.05it/s, est. speed input: 2120.78 toks/s, output: 773.90 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q4 | run 2/3: 0.594s

Rendering prompts: 100%|██████████| 4/4 [00:00<00:00, 160.33it/s]
Processed prompts: 100%|██████████| 4/4 [00:00<00:00,  6.98it/s, est. speed input: 2099.46 toks/s, output: 766.11 toks/s]

  guatemala-volcano_00000021_pre_disaster.png | Q1-Q4 | run 3/3: 0.601s
  guatemala-volcano_00000021_pre_disaster.png | run 3/3 total: 0.601s (439 tokens, 730.4 tok/s)

,experiment,use_continuous_batching,enable_prefix_caching,use_visual_token_compression,images_count,queries_per_image,runs_per_query,total_samples,mean_elapsed_s,stdev_elapsed_s,mean_output_tok_per_s,mean_first_token_latency_s,requests_per_call
4,cb_prefix_vtc,True,True,True,10,4,3,10,0.598527,0.009854,745.989931,None,4
1,continuous_batching_only,True,False,False,10,4,3,10,0.897492,0.005219,501.418140,None,4
2,prefix_caching_only,True,True,False,10,4,3,10,1.958285,0.050464,230.520906,None,4
3,visual_token_compression_only,True,False,True,10,4,3,10,1.958389,0.043775,228.215128,None,4
0,baseline,True,False,False,10,4,3,10,2.251235,0.084540,202.004746,None,4

Raw run-level metrics:

,experiment,image_name,query_idx,query_text,run_idx,elapsed_s,requests_in_call,avg_prompt_tokens,avg_output_tokens,total_output_tokens,throughput_output_tok_per_s,avg_first_token_latency_s,sample_text
0,baseline,guatemala-volcano_00000003_post_disaster.png,1,Describe this image in detail. Include scene e...,1,0.623034,1,1072.0,128.0,128,205.446108,None,"This is an aerial, high-angle satellite image ..."
1,baseline,guatemala-volcano_00000003_post_disaster.png,2,List the top 10 visible objects and where they...,1,0.617895,1,1071.0,128.0,128,207.155081,None,- A house located in the upper left portion of...
2,baseline,guatemala-volcano_00000003_post_disaster.png,3,What potential hazards or risks can you infer ...,1,0.616912,1,1066.0,128.0,128,207.485068,None,Based on the visual evidence in this satellite...
3,baseline,guatemala-volcano_00000003_post_disaster.png,4,Summarize the scene in 3 concise bullet points.,1,0.472478,1,1066.0,93.0,93,196.834734,None,- A satellite image shows a landscape with a d...
4,baseline,guatemala-volcano_00000003_post_disaster.png,1,Describe this image in detail. Include scene e...,2,0.642769,1,1072.0,128.0,128,199.138467,None,"This is an aerial, high-angle satellite image ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,cb_prefix_vtc,guatemala-volcano_00000021_pre_disaster.png,4,Summarize the scene in 3 concise bullet points.,2,0.593862,4,298.0,55.0,439,739.228859,None,- A large agricultural complex with a greenhou...
596,cb_prefix_vtc,guatemala-volcano_00000021_pre_disaster.png,1,Describe this image in detail. Include scene e...,3,0.601051,4,304.0,128.0,439,730.387547,None,This is an aerial photograph of a rural landsc...
597,cb_prefix_vtc,guatemala-volcano_00000021_pre_disaster.png,2,List the top 10 visible objects and where they...,3,0.601051,4,303.0,128.0,439,730.387547,None,- A large agricultural area with a greenhouse ...
598,cb_prefix_vtc,guatemala-volcano_00000021_pre_disaster.png,3,What potential hazards or risks can you infer ...,3,0.601051,4,298.0,128.0,439,730.387547,None,"Based on the visual information in the image, ..."
599,cb_prefix_vtc,guatemala-volcano_00000021_pre_disaster.png,4,Summarize the scene in 3 concise bullet points.,3,0.601051,4,298.0,55.0,439,730.387547,None,- A large agricultural complex with a greenhou...

In [5]:
# Save outputs for later analysis

safe_model_name = MODEL_NAME.replace("/", "_")

results_df.to_csv(f'{safe_model_name}_qwen3vl_vllm_profile_summary.csv', index=False)
raw_runs_df.to_csv(f'{safe_model_name}_qwen3vl_vllm_profile_raw_runs.csv', index=False)

with open(f'{safe_model_name}_qwen3vl_vllm_profile_summary.json', 'w', encoding='utf-8') as f:
    json.dump(summary_rows, f, indent=2)

with open(f'{safe_model_name}_qwen3vl_vllm_profile_raw_runs.json', 'w', encoding='utf-8') as f:
    json.dump(all_raw_runs, f, indent=2)

print('Saved:')
print('  ' + f'{safe_model_name}_qwen3vl_vllm_profile_summary.csv')
print('  ' + f'{safe_model_name}_qwen3vl_vllm_profile_raw_runs.csv')
print('  ' + f'{safe_model_name}_qwen3vl_vllm_profile_summary.json')
print('  ' + f'{safe_model_name}_qwen3vl_vllm_profile_raw_runs.json')

Saved:
  Qwen_Qwen3-VL-2B-Instruct_qwen3vl_vllm_profile_summary.csv
  Qwen_Qwen3-VL-2B-Instruct_qwen3vl_vllm_profile_raw_runs.csv
  Qwen_Qwen3-VL-2B-Instruct_qwen3vl_vllm_profile_summary.json
  Qwen_Qwen3-VL-2B-Instruct_qwen3vl_vllm_profile_raw_runs.json